name: Deploy Zola Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Zola
        run: |
          zola --config zola.toml build
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_BRANCH: gh-pages
